config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#top"
  get "/privacy_policy" =>"home#privacy_policy"
  get "/signup" => "users#new"
  post "/users" =>"users#create"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  post   '/login/test_user',   to: 'sessions#create_test_user'
  delete '/logout',  to: 'sessions#destroy'
  get "/works/form" => "works#form"
  get "/works/search/:year/:season" => "works#search_season"
  get "/works/search" => "works#search"
  post "/my_work/gold/:id" => "my_works#gold" 
  post "/my_work/silver/:id" => "my_works#silver" 
  post "/my_work/bronze/:id" => "my_works#bronze" 
  delete "/my_work/delete/:id" => "my_works#delete" 
  post "/my_page/my_work/gold/:id" => "my_works#my_page_gold" 
  post "/my_page/my_work/silver/:id" => "my_works#my_page_silver" 
  post "/my_page/my_work/bronze/:id" => "my_works#my_page_bronze" 
  delete "/my_page/my_work/delete/:id" => "my_works#my_page_delete" 
  get "/users/form" => "users#form"
  get "/users/search" => "users#search"
  get "/animeter/:id"=> "animeter#animeter"
  resources :users
end

app/models/work.rb
class Work < ApplicationRecord
    enum season: { winter: 1, spring: 2, summer: 3, autumn: 4, }
    has_many:my_works
  
    # Annictから情報を取得
    def import_from_annict
      base_url = "https://api.annict.com/v1"
      access_token = ENV["ANNICT_ACCESS_TOKEN"]
  
      start_year = 1970 # どの年からデータを取得したいかを指定
      end_year = Date.today.year
      seasons = ["winter","spring", "summer", "autumn"]
  
      (start_year..end_year).each do |year|
        seasons.each.with_index(1) do |season, index|
          # 初回リクエストはデータの総数を調べるために実行
          data = JSON.parse(Faraday.get("#{base_url}/works?fields=id&per_page=50&filter_season=#{year}-#{season}&sort_id=desc&access_token=#{access_token}").body)
  
          data_count = data["total_count"]         # データの数
          page_count = (data_count / 50.to_f).ceil # ページの数
  
          current_page = 1
  
          # 現在のページ <= ページの数になるまで繰り返し処理を実行
          while current_page <= page_count do
            data = JSON.parse(Faraday.get("#{base_url}/works?fields=title,season_name_text&page=#{current_page}&per_page=50&filter_season=#{year}-#{season}&sort_id=desc&access_token=#{access_token}").body)
            works = data["works"]
  
            works.each do |work|
              # すでにレコードが存在する場合は更新、無ければ新規作成
              Work.find_or_initialize_by(title: work["title"]).update(
                year: year,
                season: index,
                season_name_text: work["season_name_text"]
              )
            end
  
            current_page += 1
          end
        end
      end
    end

  def whats_rank(work_id,user_id)
    work= MyWork.find_by(work_id:work_id,user_id:user_id)
    return work  
  end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
    before_action :logged_in_user

    def form
    end

    def search
        search = params[:search]
            if search==""
                redirect_to "/works/form"
            end
        @works = Work.where('title LIKE ?', "%#{params[:search]}%") if params[:search].present?
        @title = params[:search]
    end

    def search_season
        @works= Work.where(year:params[:year],season:params[:season])
    end

    private
    def logged_in_user
        unless logged_in?
            flash[:danger] = "ログインしてください"
            redirect_to login_url
        end
    end
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/works/_rank.html.erb
<% my_work=current_user.ranked_by?(work.id,current_user.id) %>
<% if my_work %>
    <%rank=my_work["rank"]%>
    <% if rank==1 %>
        <div class="my-anime-rank-wrapper">
            <div class="my-anime-rank-area">
                <i class="fas fa-crown bronze crown"></i>
                <p class="my-anime-rank">Rank</p>
                <p class="my-anime-rank-result bronze">Bronze</p>
            </div>
            <div class="my_anime_rank_update-area">
                <i class="fas fa-sync-alt"></i>
                <%= link_to"/my_work/gold/#{work.id}", method: "post",remote: "true" do%><i class="fas fa-crown gold crown"></i><% end %>
                <%= link_to"/my_work/silver/#{work.id}", method: "post",remote: "true" do%><i class="fas fa-crown silver crown"></i><% end %>
                <%= link_to"/my_work/delete/#{work.id}", method: "delete",remote: "true" do%><i class="fas fa-trash-alt trash"></i><% end %>
            </div>   
        </div>
    <% elsif rank==2%>
        <div class="my-anime-rank-wrapper">
            <div class="my-anime-rank-area">
                <i class="fas fa-crown silver crown"></i>
                <p class="my-anime-rank ">Rank</p>
                <p class="my-anime-rank-result silver">Silver</p>
            </div>
            <div class="my_anime_rank_update-area">
                <i class="fas fa-sync-alt"></i>
                <%= link_to"/my_work/gold/#{work.id}", method: "post",remote: "true" do%><i class="fas fa-crown gold crown"></i><% end %>
                <%= link_to"/my_work/bronze/#{work.id}", method: "post",remote: "true" do%><i class="fas fa-crown bronze crown"></i><% end %>
                <%= link_to"/my_work/delete/#{work.id}", method: "delete",remote: "true" do%><i class="fas fa-trash-alt trash"></i><% end %>
            </div>   
        </div>
    <% elsif rank==3%>
        <div class="my-anime-rank-wrapper">
            <div class="my-anime-rank-area">
                <i class="fas fa-crown gold crown"></i>
                <p class="my-anime-rank">Rank</p>
                <p class="my-anime-rank-result gold">Gold</p>
            </div>
            <div class="my_anime_rank_update-area">
                <i class="fas fa-sync-alt"></i>
                <%= link_to"/my_work/silver/#{work.id}", method: "post",remote: "true" do%><i class="fas fa-crown silver crown"></i><% end %>
                <%= link_to"/my_work/bronze/#{work.id}", method: "post",remote: "true" do%><i class="fas fa-crown bronze crown"></i><% end %>
                <%= link_to"/my_work/delete/#{work.id}", method: "delete",remote: "true" do%><i class="fas fa-trash-alt trash"></i><% end %>
            </div>   
        </div>
    <%end%>
<% else%>
    <div class="my-anime-rank-wrapper">
            <div class="my-anime-rank-area">
                <p class="my-anime-rank">Rank</p>
                <p class="my-anime-none">None</p>
            </div>
            <div class="my_anime_rank_update-area">
                <i class="fas fa-plus "></i>
                <%= link_to"/my_work/gold/#{work.id}", method: "post",remote: "true" do%><i class="fas fa-crown gold crown"></i><% end %>
                <%= link_to"/my_work/silver/#{work.id}", method: "post",remote: "true" do%><i class="fas fa-crown silver crown"></i><% end %>
                <%= link_to"/my_work/bronze/#{work.id}", method: "post",remote: "true" do%><i class="fas fa-crown bronze crown"></i><% end %>
            </div>   
        </div>
<% end %>
<div class="my-anime-text-area">
    <p class="my-anime-title"><%= work.title %></p>
</div>
<div class="myanime-season_name_text-area">
    <p class="myanime-season_name_text"><%= work.season_name_text%></p>
</div>

app/views/works/form.html.erb
        <main>
            <div id="main-inner">
                <div class="search-area ">
                    <h2 id="search-title">アニメ検索</h2>
                    <div id="keyword-search-area">
                        <%= form_with url: works_search_path, method: :get, local: true ,id:"search-form" do |form| %>
                            <%= text_field_tag :search,"",{id:"sbox1"} %>
                            <%= submit_tag '検索', :name => nil ,id:"sbtn1"%>
                        <% end %>
                    </div>
                    <div id="by-year-area">
                        <h3 class="by-year-title">年代で探す</h3>
                        <div id="by-year-select-area">

                            <div class="by-year-box">
                                <h3 class="by-year-year"><a href="">2022年</a></h3>
                                <div class="by-year-season-area">
                                    <%= link_to "2022年・冬", "/works/search/2022/1", class:"by-year-season"%>
                                    <%= link_to "2022年・春", "/works/search/2022/2", class:"by-year-season"%>
                                    <%= link_to "2022年・夏", "/works/search/2022/3", class:"by-year-season"%>
                                    <%= link_to "2022年・秋", "/works/search/2022/4", class:"by-year-season"%>
                                </div>
                            </div>

                            <div class="by-year-box">
                                <h3 class="by-year-year"><a href="">2021年</a></h3>
                                <div class="by-year-season-area">
                                    <%= link_to "2021年・冬", "/works/search/2021/1", class:"by-year-season"%>
                                    <%= link_to "2021年・春", "/works/search/2021/2", class:"by-year-season"%>
                                    <%= link_to "2021年・夏", "/works/search/2021/3", class:"by-year-season"%>
                                    <%= link_to "2021年・秋", "/works/search/2021/4", class:"by-year-season"%>
                                </div>
                            </div>
                            <div class="by-year-box">
                                <h3 class="by-year-year"><a href="">2020年</a></h3>
                                <div class="by-year-season-area">
                                    <%= link_to "2020年・冬", "/works/search/2020/1", class:"by-year-season"%>
                                    <%= link_to "2020年・春", "/works/search/2020/2", class:"by-year-season"%>
                                    <%= link_to "2020年・夏", "/works/search/2020/3", class:"by-year-season"%>
                                    <%= link_to "2020年・秋", "/works/search/2020/4", class:"by-year-season"%>
                                </div>
                            </div>
                            <div class="by-year-box">
                                <h3 class="by-year-year"><a href="">2019年</a></h3>
                                <div class="by-year-season-area">
                                    <%= link_to "2019年・冬", "/works/search/2019/1", class:"by-year-season"%>
                                    <%= link_to "2019年・春", "/works/search/2019/2", class:"by-year-season"%>
                                    <%= link_to "2019年・夏", "/works/search/2019/3", class:"by-year-season"%>
                                    <%= link_to "2019年・秋", "/works/search/2019/4", class:"by-year-season"%>
                                </div>
                            </div>
                            <div class="by-year-box">
                                <h3 class="by-year-year"><a href="">2018年</a></h3>
                                <div class="by-year-season-area">
                                    <%= link_to "2018年・冬", "/works/search/2018/1", class:"by-year-season"%>
                                    <%= link_to "2018年・春", "/works/search/2018/2", class:"by-year-season"%>
                                    <%= link_to "2018年・夏", "/works/search/2018/3", class:"by-year-season"%>
                                    <%= link_to "2018年・秋", "/works/search/2018/4", class:"by-year-season"%>
                                </div>
                            </div>
                            <div class="by-year-box">
                                <h3 class="by-year-year"><a href="">2017年</a></h3>
                                <div class="by-year-season-area">
                                    <%= link_to "2017年・冬", "/works/search/2017/1", class:"by-year-season"%>
                                    <%= link_to "2017年・春", "/works/search/2017/2", class:"by-year-season"%>
                                    <%= link_to "2017年・夏", "/works/search/2017/3", class:"by-year-season"%>
                                    <%= link_to "2017年・秋", "/works/search/2017/4", class:"by-year-season"%>
                                </div>
                            </div>
                            <div class="by-year-box">
                                <h3 class="by-year-year"><a href="">2016年</a></h3>
                                <div class="by-year-season-area">
                                    <%= link_to "2016年・冬", "/works/search/2016/1", class:"by-year-season"%>
                                    <%= link_to "2016年・春", "/works/search/2016/2", class:"by-year-season"%>
                                    <%= link_to "2016年・夏", "/works/search/2016/3", class:"by-year-season"%>
                                    <%= link_to "2016年・秋", "/works/search/2016/4", class:"by-year-season"%>
                                </div>
                            </div>
                            <div class="by-year-box">
                                <h3 class="by-year-year"><a href="">2015年</a></h3>
                                <div class="by-year-season-area">
                                    <%= link_to "2015年・冬", "/works/search/2015/1", class:"by-year-season"%>
                                    <%= link_to "2015年・春", "/works/search/2015/2", class:"by-year-season"%>
                                    <%= link_to "2015年・夏", "/works/search/2015/3", class:"by-year-season"%>
                                    <%= link_to "2015年・秋", "/works/search/2015/4", class:"by-year-season"%>
                                </div>
                            </div>
                            <div class="by-year-box">
                                <h3 class="by-year-year"><a href="">2014年</a></h3>
                                <div class="by-year-season-area">
                                    <%= link_to "2014年・冬", "/works/search/2014/1", class:"by-year-season"%>
                                    <%= link_to "2014年・春", "/works/search/2014/2", class:"by-year-season"%>
                                    <%= link_to "2014年・夏", "/works/search/2014/3", class:"by-year-season"%>
                                    <%= link_to "2014年・秋", "/works/search/2014/4", class:"by-year-season"%>
                                </div>
                            </div>
                            <div class="by-year-box">
                                <h3 class="by-year-year"><a href="">2013年</a></h3>
                                <div class="by-year-season-area">
                                    <%= link_to "2013年・冬", "/works/search/2013/1", class:"by-year-season"%>
                                    <%= link_to "2013年・春", "/works/search/2013/2", class:"by-year-season"%>
                                    <%= link_to "2013年・夏", "/works/search/2013/3", class:"by-year-season"%>
                                    <%= link_to "2013年・秋", "/works/search/2013/4", class:"by-year-season"%>
                                </div>
                            </div>
                            <div class="by-year-box">
                                <h3 class="by-year-year"><a href="">2012年</a></h3>
                                <div class="by-year-season-area">
                                    <%= link_to "2012年・冬", "/works/search/2012/1", class:"by-year-season"%>
                                    <%= link_to "2012年・春", "/works/search/2012/2", class:"by-year-season"%>
                                    <%= link_to "2012年・夏", "/works/search/2012/3", class:"by-year-season"%>
                                    <%= link_to "2012年・秋", "/works/search/2012/4", class:"by-year-season"%>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>

app/views/works/search.html.erb
<main>
    <div id="main-inner">
        <div class="search-area search-result-area">
            <h2 id="search-title">「<%=@title%>」の検索結果</h2>
            <div id="keyword-search-area">
                <%= form_with url: works_search_path, method: :get, local: true ,id:"search-form" do |form| %>
                    <%= text_field_tag :search,"",{id:"sbox1"} %>
                    <%= submit_tag '検索', :name => nil ,id:"sbtn1"%>
                <% end %>
            </div>
        </div>
        <div id="anime-search-result-area">
            <% @works.each do |work| %>
                <article class="my-anime-article" id="work_<%= work.id %>" >
                    <%= render 'rank', work:work %>
                    
                </article>
            <% end%>
        </div>
    </div>
</main>

app/views/works/search_season.html.erb
<main>
    <div id="main-inner">
        <div class="search-area search-result-area">
            <h2 id="search-title">
                <%= params[:year]%>年
                <%if params[:season]=="1"%>
                    ・冬
                <%elsif params[:season]=="2"%>
                    ・春
                <%elsif params[:season]=="3"%>
                    ・夏
                <%elsif params[:season]=="4"%>
                    ・秋
                <%end%>
                のアニメ
            </h2>
        </div>
        <div id="anime-search-result-area">
            <% @works.each do |work| %>
                <article class="my-anime-article" id="work_<%= work.id %>" >
                    <%= render 'rank', work:work %>
                </article>
            <% end%>
        </div>
    </div>
</main>