config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#top"
  get "/privacy_policy" =>"home#privacy_policy"
  get "/signup" => "users#new"
  post "/users" =>"users#create"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  post   '/login/test_user',   to: 'sessions#create_test_user'
  delete '/logout',  to: 'sessions#destroy'
  get "/works/form" => "works#form"
  get "/works/search/:year/:season" => "works#search_season"
  get "/works/search" => "works#search"
  post "/my_work/gold/:id" => "my_works#gold" 
  post "/my_work/silver/:id" => "my_works#silver" 
  post "/my_work/bronze/:id" => "my_works#bronze" 
  delete "/my_work/delete/:id" => "my_works#delete" 
  post "/my_page/my_work/gold/:id" => "my_works#my_page_gold" 
  post "/my_page/my_work/silver/:id" => "my_works#my_page_silver" 
  post "/my_page/my_work/bronze/:id" => "my_works#my_page_bronze" 
  delete "/my_page/my_work/delete/:id" => "my_works#my_page_delete" 
  get "/users/form" => "users#form"
  get "/users/search" => "users#search"
  get "/animeter/:id"=> "animeter#animeter"
  resources :users
end

app/models/user.rb
class User < ApplicationRecord
    validates :Animeter_id, presence: true, length: { maximum: 20 },uniqueness:true
    validates :name, presence: true, length: { maximum: 20 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :mail, presence: true, length: { maximum: 100 },format: { with: VALID_EMAIL_REGEX },uniqueness: true
    has_secure_password 
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    mount_uploader :img, ImgUploader
    has_one_attached :img
    validate :img_content_type, if: :was_attached?
    # validates :img, presence: true

    has_many :my_works

    def ranked_by?(work_id,user_id)
        works= MyWork.find_by(work_id: work_id, user_id:user_id)
        
        return works
    end

    def img_content_type
        extension = ['image/png', 'image/jpg', 'image/jpeg','image/heic']
        errors.add(:img,"ファイルを選んでください") unless img.content_type.in?(extension)
    end

    def was_attached?
        self.img?
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @my_works = MyWork.where(user_id:params[:id])
    @my_works_log = @my_works.order(updated_at: :desc)
    @my_works_log = @my_works_log.first(10)

    @my_works = @my_works.order(rank: :desc)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      #sessions_helper#log_inメソッド

      flash[:success] = "ようこそAnimeterへ!!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    #編集内容が有効である場合
    if @user.update(user_params)
      flash[:success] = "プロフィールを更新しました"
      redirect_to @user
    #編集内容が無効である場合
    else
      render 'edit'
    end
  end

  def form
    @users = User.all  
  end

  def search
    search = params[:search]
      #空検索した時に検索フォームに戻る
      if search==""
        redirect_to "/users/form"
      end
    @users = User.where('Animeter_id LIKE ?', "%#{params[:search]}%") if params[:search].present?
    @user_name =params[:search]
  end

  private
    #permitメソッドで許可していない項目については変更されない
    def user_params
      params.require(:user).permit(:name, :mail, :password,:Animeter_id,
                                  :password_confirmation,:img)
    end

    def logged_in_user
      unless logged_in? #sessions_heiper
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end

    #他のユーザーがedit,updateするのを防ぐ
    def correct_user
      @user = User.find(params[:id])
      redirect_to("/") unless @user == current_user
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_rank.html.erb
<% if my_work %>
    <%user=my_work.who_user(my_work.user_id)%>
    <%if my_work.rank==1%>
        <div class="my-anime-rank-wrapper">
            <div class="my-anime-rank-area">
                <i class="fas fa-crown bronze crown"></i>
                <p class="my-anime-rank">Rank</p>
                <p class="my-anime-rank-result bronze">Bronze</p>
            </div>
            <%if current_user%>
                <%if user.id==current_user.id%>
                    <div class="my_anime_rank_update-area">
                    <i class="fas fa-sync-alt"></i>
                    <%= link_to"/my_page/my_work/gold/#{work.id}", method: "post",remote: "true" do%><i class="fas fa-crown gold crown"></i><% end %>
                    <%= link_to"/my_page/my_work/silver/#{work.id}", method: "post",remote: "true" do%><i class="fas fa-crown silver crown"></i><% end %>
                    <%= link_to"/my_page/my_work/delete/#{work.id}", method: "delete",remote: "true" do%><i class="fas fa-trash-alt trash"></i><% end %>
                    </div>  
                <%end%>
            <%end%>
        </div>
    <%elsif my_work.rank==2%>
            <div class="my-anime-rank-wrapper">
                <div class="my-anime-rank-area">
                    <i class="fas fa-crown silver crown"></i>
                    <p class="my-anime-rank">Rank</p>
                    <p class="my-anime-rank-result silver">Silver</p>
                </div>
                <%if current_user%>
                    <%if user.id==current_user.id%>
                        <div class="my_anime_rank_update-area">
                            <i class="fas fa-sync-alt"></i>
                            <%= link_to"/my_page/my_work/gold/#{work.id}", method: "post",remote: "true" do%><i class="fas fa-crown gold crown"></i><% end %>
                            <%= link_to"/my_page/my_work/bronze/#{work.id}", method: "post",remote: "true" do%><i class="fas fa-crown bronze crown"></i><% end %>
                            <%= link_to"/my_page/my_work/delete/#{work.id}", method: "delete",remote: "true" do%><i class="fas fa-trash-alt trash"></i><% end %>
                        </div>   
                    <%end%>
                <%end%>
            </div>
    <%elsif my_work.rank==3%>
            <div class="my-anime-rank-wrapper">
                <div class="my-anime-rank-area">
                    <i class="fas fa-crown gold crown"></i>
                    <p class="my-anime-rank">Rank</p>
                    <p class="my-anime-rank-result gold">Gold</p>
                </div>
                <%if current_user%>
                    <%if user.id==current_user.id%>
                        <div class="my_anime_rank_update-area">
                            <i class="fas fa-sync-alt"></i>
                            <%= link_to"/my_page/my_work/silver/#{work.id}", method: "post",remote: "true" do%><i class="fas fa-crown silver crown"></i><% end %>
                            <%= link_to"/my_page/my_work/bronze/#{work.id}", method: "post",remote: "true" do%><i class="fas fa-crown bronze crown"></i><% end %>
                            <%= link_to"/my_page/my_work/delete/#{work.id}", method: "delete",remote: "true" do%><i class="fas fa-trash-alt trash"></i><% end %>
                        </div>   
                    <%end%>
                <%end%>
            </div>
    <%end%>
<%else%>
    <div class="my-anime-rank-wrapper">
        <div class="my-anime-rank-area">
            <p class="my-anime-rank">Rank</p>
            <p class="my-anime-none">None</p>
        </div>
        <div class="my_anime_rank_update-area">
            <i class="fas fa-plus "></i>
            <%= link_to"/my_page/my_work/gold/#{work.id}", method: "post",remote: "true" do%><i class="fas fa-crown gold crown"></i><% end %>
            <%= link_to"/my_page/my_work/silver/#{work.id}", method: "post",remote: "true" do%><i class="fas fa-crown silver crown"></i><% end %>
            <%= link_to"/my_page/my_work/bronze/#{work.id}", method: "post",remote: "true" do%><i class="fas fa-crown bronze crown"></i><% end %>
        </div> 
    </div>
<%end%>
        <div class="my-anime-text-area">
            <p class="my-anime-title"><%=work.title%></p>
        </div>
        <div class="myanime-season_name_text-area">
            <p class="myanime-season_name_text"><%= work.season_name_text%></p>
        </div>

app/views/users/edit.html.erb
<main>
    <div class="main-inner">
        <div class="create-form-wrapper">
            <h1>ユーザー情報編集</h1>
            <%= form_with(model: @user, local: true) do |f| %>
                <%= render 'shared/error_messages' %>
                <div class="form-item">
                    <%= f.label :ユーザー名 %>
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
                
                <div class="form-item">
                    <%= f.label :検索用ID %>
                    <%= f.text_field :Animeter_id%>
                </div>

                <div class="form-item">
                    <%= f.label :Email %>
                    <%= f.email_field :mail%>
                </div>

                <div class="form-item">
                    <%= f.label :パスワード %>
                    <%= f.password_field :password%>
                </div>

                <div class="form-item">
                    <%= f.label :password_confirmation, "パスワード（確認）" %>
                    <%= f.password_field :password_confirmation%>
                </div>

                <div class="form-img">
                    <%= f.label :img, "プロフィール画像" %>
                    <%= f.file_field :img%>
                </div>
                
                <div class="button-panel">
                    <%= f.submit "登録", class:"button" %>
                </div>
            <% end %>
        </div>
    </div>
</main>

app/views/users/form.html.erb
        <main>
            <div id="main-inner">
                <div class="search-area search-result-area">
                    <h2 id="search-title">ユーザー検索</h2>
                    <div id="keyword-search-area">
                        <%= form_with url: users_search_path, method: :get, local: true ,id:"search-form" do |form| %>
                            <%= text_field_tag :search,"",{id:"sbox1"} %>
                            <%= submit_tag '検索', :name => nil ,id:"sbtn1"%>
                        <% end %>
                    </div>
                    <p class="test-user"><%= link_to "Animeter開発者とAnimeter!","/animeter/1"%></p>
                </div>
                <div id="user-search-result-area">
                    <h3 class="user-list">User List</h3>
                    <% @users.each do |user| %>
                        <article class="user-article">
                            <%= link_to"/users/#{user.id}" do%>
                                <div class="user-search-result-img-area">
                                    <%= image_tag "#{user.img}" , class: "user-search-result-img"%>
                                </div>
                                <div class="user-search-result-name-area">
                                    <p class="user-search-result-name"><%= user.name %></p>
                                    <p class="user-search-result-id"><%= user.Animeter_id %></p>
                                </div>
                            <% end %>
                        </article>
                    <% end%>
                </div>
            </div>
        </main>

app/views/users/new.html.erb
<main>
    <div id="main-inner">
        <div class="create-form-wrapper">
            <h1>ユーザー新規登録</h1>
            <%= form_with(model: @user, local: true) do |f| %>
                <%= render 'shared/error_messages' %>
                <div class="form-item">
                    <%= f.label :name ,"ユーザー名" %>
                    <%= f.text_field :name, class: 'form-control' %>
                </div>
                
                <div class="form-item">
                    <%= f.label :Animeter_id,"検索用ID" %>
                    <%= f.text_field :Animeter_id%>
                </div>

                <div class="form-item">
                    <%= f.label :mail,"Email" %>
                    <%= f.email_field :mail%>
                </div>

                <div class="form-item">
                    <%= f.label :password,"パスワード" %>
                    <%= f.password_field :password%>
                </div>

                <div class="form-item">
                    <%= f.label :password_confirmation, "パスワード（確認）" %>
                    <%= f.password_field :password_confirmation%>
                </div>

                <div class="form-img">
                    <%= f.label :img, "プロフィール画像" %>
                    <%= f.file_field :img%>
                </div>

                <div class="button-panel">
                    <%= f.submit "登録", class:"button" %>
                </div>
            <% end %>
        </div>
        <p class="test-user"><%= link_to "テストユーザーでログイン","/login/test_user",method: "post" %></p>
        
    </div>
</main>

app/views/users/search.html.erb
<main>
    <div id="main-inner">
        <div class="search-area search-result-area">
            <h2 id="search-title"><%=@user_name%>の検索結果</h2>
            <div id="keyword-search-area">
                <%= form_with url: users_search_path, method: :get, local: true ,id:"search-form" do |form| %>
                    <%= text_field_tag :search,"",{id:"sbox1"} %>
                    <%= submit_tag '検索', :name => nil ,id:"sbtn1"%>
                <% end %>
            </div>
        </div>
        <div id="user-search-result-area">
            <% @users.each do |user| %>
                
                    <article class="user-article">
                        <%= link_to"/users/#{user.id}" do%>
                            <div class="user-search-result-img-area">
                                <%= image_tag "#{user.img}" , class: "user-search-result-img"%>
                            </div>
                            <div class="user-search-result-name-area">
                                <p class="user-search-result-name"><%= user.name %></p>
                                <p class="user-search-result-id"><%= user.Animeter_id %></p>
                            </div>
                        <% end %>
                    </article>
                
            <% end%>
        </div>
    </div>
</main>

app/views/users/show.html.erb
        <main>
            <div id="main-inner">
                <div class="mypage-area">
                    <div class="profile-area">
                        <div class="my-img-area">
                            <%= image_tag "#{@user.img}" , class: "my-img"%>
                        </div>
                        <div class="my-name-area">
                            <p class="my-name"><%= @user.name %></p>
                            <p class="my-id"><%= @user.Animeter_id %></p>
                        </div>
                        <%if current_user%>
                            <%if @user.id==current_user.id%>
                                <%if current_user.Animeter_id=="test"%>
                                <%else%>
                                    <div class="profile-btn-area">
                                        <%= link_to "プロフィール編集", "/users/#{@user.id}/edit", class: "profile-btn"%>
                                    </div>
                                <%end%>
                            <%else%>
                                <div class="profile-btn-area">
                                    <%= link_to "Animeterを実行", "/animeter/#{@user.id}", class: "profile-btn"%>
                                </div>
                            <%end%>
                        <%end%>
                    </div>
                    <div class="my-anime-area">
                        <div class="my-anime-area-inner">
                            <div class="tabs">
                                <input id="left" type="radio" name="tab_item" checked>
                                <label class="tab_item" for="left">アニメログ</label>
                                <input id="right" type="radio" name="tab_item">
                                <label class="tab_item" id="rspec-tab" for="right">登録アニメ</label>
                                <div class="tab_content" id="left_content">
                                    <div class="tab_content_description">
                                        <% @my_works_log.each do |my_work_log| %>
                                            <%my_work= my_work_log.whats_work(my_work_log.work_id)%>
                                            <article class="my-animelog-article">
                                                <div class="animelog-name-area">
                                                    <%= image_tag "#{@user.img}" , class: "animelog-my-img"%>
                                                    <p class="my-animelog-my-name"><%= @user.name %></p>
                                                </div>
                                                <div class="animelog-text-area">
                                                    <p class="animelog-anime-title"><%=my_work.title%></p>
                                                    <p class="animelog-register">を登録しました</p>
                                                </div>
                                                <div class="animelog-bottom-area">
                                                    <div class="animelog-rank-area">
                                                        <p class="animelog-rank">Rank</p>
                                                        <%if my_work_log.rank==1%>
                                                            <p class="animelog-rank-name bronze">Bronz</p>
                                                        <%elsif my_work_log.rank==2%>
                                                            <p class="animelog-rank-name silver">Silver</p>
                                                        <%elsif my_work_log.rank==3%>
                                                            <p class="animelog-rank-name gold">Gold</p>
                                                        <%end%>
                                                    </div>
                                                    <div class="animelog-time-area">
                                                        <p class="animelog-time"><%=my_work_log.updated_at.strftime('%Y/%m/%d %H:%M')%></p>
                                                    </div>
                                                </div>
                                            </article>
                                        <% end %>
                                    </div>
                                </div>
                                <div class="tab_content" id="right_content">
                                  <div class="tab_content_description">
                                    <% @my_works.each do |my_work| %>
                                        <%work=my_work.whats_work(my_work.work_id)%>
                                        <article class="my-anime-article" id="my_work_<%= work.id%>" %>
                                            <%= render 'rank', my_work:my_work,work:work %>
                                        </article>
                                    <% end%>
                                  </div>
                                </div>
                              </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>