config/routes.rb
Rails.application.routes.draw do
  get "/" => "home#top"
  get "/privacy_policy" =>"home#privacy_policy"
  get "/signup" => "users#new"
  post "/users" =>"users#create"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  post   '/login/test_user',   to: 'sessions#create_test_user'
  delete '/logout',  to: 'sessions#destroy'
  get "/works/form" => "works#form"
  get "/works/search/:year/:season" => "works#search_season"
  get "/works/search" => "works#search"
  post "/my_work/gold/:id" => "my_works#gold" 
  post "/my_work/silver/:id" => "my_works#silver" 
  post "/my_work/bronze/:id" => "my_works#bronze" 
  delete "/my_work/delete/:id" => "my_works#delete" 
  post "/my_page/my_work/gold/:id" => "my_works#my_page_gold" 
  post "/my_page/my_work/silver/:id" => "my_works#my_page_silver" 
  post "/my_page/my_work/bronze/:id" => "my_works#my_page_bronze" 
  delete "/my_page/my_work/delete/:id" => "my_works#my_page_delete" 
  get "/users/form" => "users#form"
  get "/users/search" => "users#search"
  get "/animeter/:id"=> "animeter#animeter"
  resources :users
end

app/views/layouts/_layout.html.slim
html
  head
    = display_meta_tags(default_meta_tags)

  body
    == yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= display_meta_tags(default_meta_tags) %>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">

        <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
        <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
        <%=csrf_meta_tags%>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-G2S0FVN13S"></script>
        <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-G2S0FVN13S');
        </script>
    </head>
    
    <body>
        <header>
            <div id="header-inner">
                <% if logged_in? %>
                    <h1 class="header-logo-wrapper">
                        <%= link_to current_user do%><%= image_tag 'ロゴ３.png' , id: "header-logo"%><%end%>
                    </h1>
                <%else%>
                    <h1 class="header-logo-wrapper">
                        <%= link_to "/" do%><%= image_tag 'ロゴ３.png' , id: "header-logo"%><%end%>
                    </h1>
                <%end%>
                
                <nav id="header-nav">
                    <ul id="header-ul">
                        <% if logged_in? %>
                            <li class="header-li"><%= link_to "マイページ", current_user , class: "btn btn--orange"%></li>
                            <li class="header-li-sp"><%= link_to "ログアウト", logout_path, method:"delete",id: "logout-rspec" %></li>
                            <li class="header-li">
                                <input type="checkbox" id="cp_navimenuid">
                                <label class="menu" for="cp_navimenuid">
                                    <div class="menubar">
                                        <span class="bar"></span>
                                        <span class="bar"></span>
                                        <span class="bar"></span>
                                    </div>
                                    <ul>
                                        <li><%= link_to "ユーザー検索","/users/form"%></li>
                                        <li><%= link_to "アニメ検索","/works/form"%></li>
                                        <li><%= link_to "ログアウト", logout_path, method:"delete" %></li>
                                    </ul>
                                </label>
                            </li>
                        <% else %>
                            <li class="header-li-home"><%= link_to "新規登録", signup_path, class: "btn btn--orange" , id: "header-li"%></li>
                            <li class="header-li-home"><%= link_to "ログイン", login_path, class: "btn btn--orange" , id: "header-li"%></li>
                        <% end %>
                    </ul>
                </nav>
            </div>
        </header>
        <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
        <footer id="footer-pc">
            <div id="footer-pc-inner">
                <p>©︎2021Animeter</p>
                <%= link_to "プライバシーポリシー" ,"/privacy_policy" %>
            </div>
        </footer>
        <footer id="footer-sp">
            <div id="footer-sp-inner">
                <ul id="footer-sp-ul">
                    <li class="footer-sp-li"><%= link_to "/users/form" do%><i class="fas fa-users"></i><%end%></li>
                    <li class="footer-sp-li"><%= link_to current_user do%><i class="fas fa-home"></i><%end%></li>
                    <li class="footer-sp-li"><%= link_to "/works/form" do%><i class="fas fa-tv"></i><%end%></li>
                </ul>
            </div>
        </footer>

        <%= debug(params) if Rails.env.development? %>

    </body>

</html>